### ISSUE TITLE
Lost various buttons in 0.4.13

### ISSUE THREAD

**Issue by mzch** [ihexxa/quickshare#100]
After updaing from `0.4.12` to `0.4.13`, various buttons are lost.

- 0.4.12
![ScreenShot2](https://user-images.githubusercontent.com/621178/140037063-818f496d-c071-4b22-b061-02d81f62fc4f.png)

- 0.4.13
<img width="1498" alt="ScreenShot1" src="https://user-images.githubusercontent.com/621178/140037088-090720d7-0b0f-4e4f-804c-abe152dcb0c0.png">

Could you please fix this?

Server: Debian `11.1`
OS: macOS `12.0.1`
Browser: Chrome `95.0.4638.69`

**Comment by ihexxa** [comment]
@mzch sorry for this, this is on my list.

**Comment by ihexxa** [comment]
@mzch Because user preference is introduced in the 0.4.13, which is incompatible with previous user profile format in the db (<= 0.4.12). This is a breaking change which causes the issue.

I've enable a checker which tries to fix these in starting server, also feature such as friendly error reporting may be also introduced in the future.
Thank you for the detailed feedback.
