### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mzch** [ihexxa/quickshare#147]
After updating quickshare from `v0.7.1` to `v0.8.1`, I can't login.
Could you tell me how to fix this issue.

**Comment by ihexxa** [comment]
Hi @mzch,

Because 0.8.1 contains some BREAKING changes so it is not compatible with previous version. Probably it is not able to read authentication information from the existing db. Sorry for introducing the inconvenience.

Pls try to:
 - Remove the quickshare.db
 - Start the Quickshare with environments: `DEFAULTADMIN=<your admin name>  DEFAULTADMINPWD=<your password> ./quickshare -c <your config path>`
 - Input DEFAULTADMIN and  DEFAULTADMINPWD and login by clicking the login button (there may be a regression of hotkey Enter, still checking)

Let me know if it works and logs after starting may help.

**Comment by mzch** [comment]
Hi @ihexxa , thanks for your kind advice! This issue has been fixed.
